// AUTO-GENERATED by scripts/extract-questions.mjs — do not edit by hand.
export type Answer = { text: string; points: number };
export type Question = { id: string; prompt: string; answers: Answer[] };

export const QUESTIONS: Question[] = [
  {
    "id": "q1",
    "prompt": "Name a reason someone might go on mute during a meeting.",
    "answers": [
      {
        "text": "Pets / Dogs barking / Animal noise",
        "points": 28
      },
      {
        "text": "Coughing / Sneezing / Clearing throat",
        "points": 26
      },
      {
        "text": "Background noise (general / audio issues)",
        "points": 15
      },
      {
        "text": "Family / Kids / Someone interrupting",
        "points": 12
      },
      {
        "text": "Let someone else talk / side conversations",
        "points": 6
      }
    ]
  },
  {
    "id": "q2",
    "prompt": "Name something that distracts people during virtual meetings.",
    "answers": [
      {
        "text": "Pets / Animals",
        "points": 30
      },
      {
        "text": "Other people on screen (backgrounds, cameras, not muted, movement)",
        "points": 18
      },
      {
        "text": "Emails / Notifications / Messages",
        "points": 16
      },
      {
        "text": "Phones / Cell phones / Calls",
        "points": 10
      },
      {
        "text": "Kids / Children",
        "points": 9
      }
    ]
  },
  {
    "id": "q3",
    "prompt": "Name something that screams ‘working from home.’",
    "answers": [
      {
        "text": "Pajamas / Sweatpants / Comfy clothes",
        "points": 41
      },
      {
        "text": "Pets / Animals on screen or making noise",
        "points": 13
      },
      {
        "text": "Background (bed, virtual background, home setting)",
        "points": 11
      },
      {
        "text": "Kids / Family interruptions",
        "points": 7
      },
      {
        "text": "Camera-off / poor video / not on camera",
        "points": 5
      }
    ]
  },
  {
    "id": "q4",
    "prompt": "Name something every remote employee owns too many of.",
    "answers": [
      {
        "text": "Coffee cups / mugs / tumblers",
        "points": 26
      },
      {
        "text": "Sweatpants / comfy clothes",
        "points": 23
      },
      {
        "text": "Office Supplies (pens, sticky notes, notebooks)",
        "points": 18
      },
      {
        "text": "Chargers / cords / cables",
        "points": 9
      },
      {
        "text": "Water bottles / drink containers",
        "points": 5
      }
    ]
  },
  {
    "id": "q5",
    "prompt": "Name something that causes last-minute stress before a deadline.",
    "answers": [
      {
        "text": "Clients (late, unresponsive, last-minute requests)",
        "points": 28
      },
      {
        "text": "Computer / IT / Internet issues",
        "points": 19
      },
      {
        "text": "Missing / late / incorrect data",
        "points": 14
      },
      {
        "text": "Emails / communication delays",
        "points": 11
      },
      {
        "text": "Too much work / not enough time / last-minute requests",
        "points": 10
      }
    ]
  },
  {
    "id": "q6",
    "prompt": "Name something you hear in almost every client call.",
    "answers": [
      {
        "text": "“Can you hear me?” / audio issues / mute comments",
        "points": 11
      },
      {
        "text": "Questions (“I have a question,” “how do I…,” “what does that mean?”)",
        "points": 10
      },
      {
        "text": "Confusion / lack of understanding (“I don’t know,” “I don’t understand”)",
        "points": 9
      },
      {
        "text": "Thanks / greetings / pleasantries",
        "points": 8
      },
      {
        "text": "Follow-up / next steps language",
        "points": 6
      }
    ]
  },
  {
    "id": "q7",
    "prompt": "Name a word or phrase that makes an RPC immediately nervous.",
    "answers": [
      {
        "text": "Urgency (“urgent,” “ASAP,” “I need this today”)",
        "points": 9
      },
      {
        "text": "“Can we talk?” / “Do you have a minute?” / quick call requests",
        "points": 8
      },
      {
        "text": "Errors / mistakes / something is wrong",
        "points": 8
      },
      {
        "text": "Government / compliance issues (IRS, DOL, audit, PBGC)",
        "points": 7
      },
      {
        "text": "Request for documents / plan info",
        "points": 6
      }
    ]
  },
  {
    "id": "q8",
    "prompt": "Name a word or phrase that makes sales immediately nervous.",
    "answers": [
      {
        "text": "“No” / not interested / going another direction",
        "points": 12
      },
      {
        "text": "Cost / fees / pricing questions",
        "points": 10
      },
      {
        "text": "Cancel / terminate / lost client",
        "points": 9
      },
      {
        "text": "Hesitation (“I need to think about it”)",
        "points": 7
      },
      {
        "text": "Problems / complaints / service issues",
        "points": 6
      }
    ]
  },
  {
    "id": "q9",
    "prompt": "Name something people forget to bring when traveling for work.",
    "answers": [
      {
        "text": "Chargers / charging cords",
        "points": 38
      },
      {
        "text": "Mouse / computer accessories",
        "points": 9
      },
      {
        "text": "Toiletries (toothbrush, toothpaste, etc.)",
        "points": 9
      },
      {
        "text": "Laptop / computer",
        "points": 4
      },
      {
        "text": "Headphones / earbuds",
        "points": 3
      }
    ]
  },
  {
    "id": "q10",
    "prompt": "Name something people overpack when they are traveling for work.",
    "answers": [
      {
        "text": "Clothes / outfits",
        "points": 42
      },
      {
        "text": "Underwear",
        "points": 9
      },
      {
        "text": "Shoes",
        "points": 8
      },
      {
        "text": "Socks",
        "points": 4
      },
      {
        "text": "Snacks / food",
        "points": 3
      }
    ]
  },
  {
    "id": "q11",
    "prompt": "Name something people always snack on at work.",
    "answers": [
      {
        "text": "Chips",
        "points": 28
      },
      {
        "text": "Candy / chocolate / sweets",
        "points": 25
      },
      {
        "text": "Popcorn",
        "points": 12
      },
      {
        "text": "Nuts / trail mix / seeds",
        "points": 12
      },
      {
        "text": "Pretzels / crackers",
        "points": 10
      }
    ]
  },
  {
    "id": "q12",
    "prompt": "Name a song that gets everyone singing.",
    "answers": [
      {
        "text": "Sweet Caroline",
        "points": 34
      },
      {
        "text": "YMCA",
        "points": 10
      },
      {
        "text": "Don’t Stop Believin’",
        "points": 8
      },
      {
        "text": "We Are the Champions",
        "points": 4
      },
      {
        "text": "Happy Birthday",
        "points": 3
      }
    ]
  },
  {
    "id": "q13",
    "prompt": "Name something people do to procrastinate.",
    "answers": [
      {
        "text": "Scroll phone / social media / doomscroll",
        "points": 28
      },
      {
        "text": "Clean / organize / do chores",
        "points": 9
      },
      {
        "text": "Eat / snack / get coffee",
        "points": 9
      },
      {
        "text": "Do other (easier) work / avoid main task",
        "points": 8
      },
      {
        "text": "Take a break / walk / nap",
        "points": 7
      }
    ]
  },
  {
    "id": "q14",
    "prompt": "Name something people say when they don’t understand something.",
    "answers": [
      {
        "text": "“What?” / “Huh?” / confused reactions",
        "points": 18
      },
      {
        "text": "“Can you repeat that?” / “Say that again”",
        "points": 14
      },
      {
        "text": "“I don’t understand” / “I’m confused”",
        "points": 13
      },
      {
        "text": "“Can you explain/clarify that?”",
        "points": 8
      },
      {
        "text": "“Let me get back to you” / avoidance responses",
        "points": 6
      }
    ]
  },
  {
    "id": "q15",
    "prompt": "Name something that takes longer than it should at work.",
    "answers": [
      {
        "text": "Meetings",
        "points": 12
      },
      {
        "text": "Emails / email responses / email management",
        "points": 11
      },
      {
        "text": "Computer / system / login issues",
        "points": 10
      },
      {
        "text": "Getting information / client responses / follow-ups",
        "points": 7
      },
      {
        "text": "Finding/opening files / navigating systems",
        "points": 6
      }
    ]
  },
  {
    "id": "q16",
    "prompt": "Name something that always needs a follow-up email.",
    "answers": [
      {
        "text": "Data requests / census / client information",
        "points": 34
      },
      {
        "text": "Signatures / documents needing approval",
        "points": 9
      },
      {
        "text": "Client questions / calls / inquiries",
        "points": 8
      },
      {
        "text": "Proposals / sales-related items",
        "points": 6
      },
      {
        "text": "Meetings / meeting-related follow-ups",
        "points": 5
      }
    ]
  },
  {
    "id": "q17",
    "prompt": "Name something that makes HR sweat.",
    "answers": [
      {
        "text": "Employee issues / complaints / conflicts",
        "points": 18
      },
      {
        "text": "Employees quitting / turnover / terminations",
        "points": 9
      },
      {
        "text": "Tali (and Tali-related comments)",
        "points": 6
      },
      {
        "text": "Payroll issues / errors",
        "points": 6
      },
      {
        "text": "Harassment / legal / serious HR issues",
        "points": 6
      }
    ]
  },
  {
    "id": "q18",
    "prompt": "Name something that proves someone lives in a different part of the country.",
    "answers": [
      {
        "text": "Accent / dialect / way of speaking",
        "points": 32
      },
      {
        "text": "Time zone / work hours differences",
        "points": 16
      },
      {
        "text": "Weather / climate differences",
        "points": 14
      },
      {
        "text": "Regional phrases (soda vs pop, “y’all,” etc.)",
        "points": 6
      },
      {
        "text": "Clothing / appearance based on climate",
        "points": 4
      }
    ]
  },
  {
    "id": "q19",
    "prompt": "Name something people from different states argue about.",
    "answers": [
      {
        "text": "Sports teams / sports",
        "points": 32
      },
      {
        "text": "Weather / temperature",
        "points": 22
      },
      {
        "text": "Food / restaurants / regional food",
        "points": 15
      },
      {
        "text": "Politics",
        "points": 6
      },
      {
        "text": "Soda vs pop (regional wording)",
        "points": 6
      }
    ]
  },
  {
    "id": "q20",
    "prompt": "Name something people Google at work that isn’t work-related.",
    "answers": [
      {
        "text": "Weather",
        "points": 26
      },
      {
        "text": "News / current events",
        "points": 11
      },
      {
        "text": "Food / restaurants / menus",
        "points": 10
      },
      {
        "text": "Travel / vacations",
        "points": 7
      },
      {
        "text": "Sports / scores / stats",
        "points": 7
      }
    ]
  },
  {
    "id": "q21",
    "prompt": "Name something people blame technology for.",
    "answers": [
      {
        "text": "Slow systems / lag / performance issues",
        "points": 28
      },
      {
        "text": "Being late / delays / missed deadlines",
        "points": 12
      },
      {
        "text": "Email / communication issues",
        "points": 10
      },
      {
        "text": "Mistakes / lost work / deleted files",
        "points": 9
      },
      {
        "text": "Internet / connection issues",
        "points": 6
      }
    ]
  },
  {
    "id": "q22",
    "prompt": "Name something people do when their computer freezes.",
    "answers": [
      {
        "text": "Restart / reboot / force quit",
        "points": 17
      },
      {
        "text": "Yell / scream / curse",
        "points": 16
      },
      {
        "text": "Panic / stress / frustration reactions",
        "points": 10
      },
      {
        "text": "Keep clicking / hitting things",
        "points": 9
      },
      {
        "text": "Walk away / take a break",
        "points": 9
      }
    ]
  },
  {
    "id": "q23",
    "prompt": "Name something people drink during the workday.",
    "answers": [
      {
        "text": "Coffee",
        "points": 52
      },
      {
        "text": "Water",
        "points": 27
      },
      {
        "text": "Tea",
        "points": 3
      },
      {
        "text": "Soda",
        "points": 3
      },
      {
        "text": "Alcohol (joking)",
        "points": 2
      }
    ]
  },
  {
    "id": "q24",
    "prompt": "Name something people forget to do before a meeting.",
    "answers": [
      {
        "text": "Prepare / review notes / get organized",
        "points": 18
      },
      {
        "text": "Mute / unmute / manage microphone",
        "points": 15
      },
      {
        "text": "Use the bathroom",
        "points": 11
      },
      {
        "text": "Appearance (hair, clothes, camera-ready)",
        "points": 10
      },
      {
        "text": "Tech setup (camera/audio/equipment)",
        "points": 8
      }
    ]
  },
  {
    "id": "q25",
    "prompt": "Name something people pretend to know how to do.",
    "answers": [
      {
        "text": "Excel / spreadsheets / formulas",
        "points": 20
      },
      {
        "text": "Their job / work responsibilities",
        "points": 7
      },
      {
        "text": "Technology / systems / tools",
        "points": 7
      },
      {
        "text": "Cooking",
        "points": 4
      },
      {
        "text": "Math / calculations",
        "points": 4
      }
    ]
  }
];
